from typing import Annotated, Optional
from typing_extensions import TypedDict
from langgraph.graph import MessagesState, add_messages

from tradingagents.evidence.ledger import evidence_reducer


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # 每个分析师分支独占的工具循环消息通道（R1 隔离）。并行分支若共享单一
    # ``messages`` 通道，ToolNode 会读到其他分支的 AIMessage 并按它执行工具，
    # 造成工具请求/响应错配与 "not a valid tool" 错误。分析师节点、条件路由
    # 与工具节点（由 GraphSetup 统一包装）全程一致使用 ``{role}_messages``。
    market_messages: Annotated[list, add_messages]
    social_messages: Annotated[list, add_messages]
    news_messages: Annotated[list, add_messages]
    fundamentals_messages: Annotated[list, add_messages]
    policy_messages: Annotated[list, add_messages]
    hot_money_messages: Annotated[list, add_messages]
    lockup_messages: Annotated[list, add_messages]

    # C1: 证据账本——各分支工具节点把本次执行的 ToolMessage artifact 以
    # 增量（delta）写入，reducer 不可变合并：事件以 ``{role}:{tool_call_id}``
    # 为稳定身份（重放不倍增），run_id 不匹配的增量整体拒绝（并发运行/
    # 陈旧线程不串证据），输出顺序确定（并发分支写入顺序不影响结果）。
    # 旧 state 无此字段 → 兼容（保持 None，工具不写入时不产生）。
    evidence_bundle: Annotated[Optional[dict], evidence_reducer]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    policy_report: Annotated[str, "Report from the Policy Analyst (A-stock specific)"]
    hot_money_report: Annotated[str, "Report from the Hot Money Tracker (A-stock specific)"]
    lockup_report: Annotated[str, "Report from the Lockup/Reduction Watcher (A-stock specific)"]

    # data quality gate
    data_quality_summary: Annotated[str, "Quality gate assessment of all analyst reports (hard checks + LLM review)"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
    # A10: 本次启用且适用的分析师集合（质量门控只检查这些角色；未启用
    # 角色不计失败、不进提示词）。运行入口初始化，恢复路径随 checkpoint。
    selected_analysts: Annotated[list, "Analyst roles active in this run"]
    # N01: 结构化报告质量卡（JSON 可序列化；复用质量门控硬检查，单一评级
    # 来源）。旧 state 无此字段 → 兼容原行为（unknown，不凭空生成通过）。
    data_quality: Annotated[dict, "Structured report-completeness card (N01)"]
    # N02: 本次运行的身份与公开配置档案。SQLite 恢复保留原 ID/配置/时间；
    # 旧断点缺失时标示未记录，不得以恢复时配置伪装原配置。
    run_metadata: Annotated[dict, "Run identity and public config profile (N02)"]
    # C2: 研究假设卡——组合经理既有结构化调用产出的结论结构化记录（引用
    # 校验/评估状态/uncalibrated 全部代码确定性生成）。仅 PM 写入；旧 state
    # 无此字段 → 兼容（None，展示端显示未记录）。
    thesis_card: Annotated[Optional[dict], "Structured research thesis card (C2)"]
    # D1: 可复算财务面板——离线 manifest 经纯函数计算的确定性卡片；图内
    # 无人写入（D2 再接显式注入），默认缺失 → 兼容（None=未记录）。
    financial_panel: Annotated[Optional[dict], "Reproducible financial panel card (D1)"]
    # E: 独立初判与有界反证补查（默认关闭 → 字段缺失 = 旧行为）。两个初判
    # 字段由并行互盲节点各自写入；evidence_debate 汇总分歧/补查/usage 并随
    # checkpoint 持久化（恢复不重跑已消费槽位、不重置预算）。
    initial_view_bull: Annotated[Optional[dict], "Bull independent initial view (E)"]
    initial_view_bear: Annotated[Optional[dict], "Bear independent initial view (E)"]
    evidence_debate: Annotated[Optional[dict], "Disagreement plan + bounded rechecks + usage (E)"]
    # F2: 历史经验只读投影——独立持久 payload（不拼入 past_context）；fresh
    # 准备期构建，恢复只读校验。缺省（未配置 review_records_path）→ 字段缺
    # 失 = 旧行为。
    review_projection: Annotated[Optional[dict], "Read-only review-record projection (F2)"]
