from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import MessagesState, add_messages


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # 每个分析师分支独占的工具循环消息通道（R1 隔离）。并行分支若共享单一
    # ``messages`` 通道，ToolNode 会读到其他分支的 AIMessage 并按它执行工具，
    # 造成工具请求/响应错配与 "not a valid tool" 错误。分析师节点、条件路由
    # 与工具节点（由 GraphSetup 统一包装）全程一致使用 ``{role}_messages``。
    market_messages: Annotated[list, add_messages]
    social_messages: Annotated[list, add_messages]
    news_messages: Annotated[list, add_messages]
    fundamentals_messages: Annotated[list, add_messages]
    policy_messages: Annotated[list, add_messages]
    hot_money_messages: Annotated[list, add_messages]
    lockup_messages: Annotated[list, add_messages]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    policy_report: Annotated[str, "Report from the Policy Analyst (A-stock specific)"]
    hot_money_report: Annotated[str, "Report from the Hot Money Tracker (A-stock specific)"]
    lockup_report: Annotated[str, "Report from the Lockup/Reduction Watcher (A-stock specific)"]

    # data quality gate
    data_quality_summary: Annotated[str, "Quality gate assessment of all analyst reports (hard checks + LLM review)"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
    # A10: 本次启用且适用的分析师集合（质量门控只检查这些角色；未启用
    # 角色不计失败、不进提示词）。运行入口初始化，恢复路径随 checkpoint。
    selected_analysts: Annotated[list, "Analyst roles active in this run"]
    # N01: 结构化报告质量卡（JSON 可序列化；复用质量门控硬检查，单一评级
    # 来源）。旧 state 无此字段 → 兼容原行为（unknown，不凭空生成通过）。
    data_quality: Annotated[dict, "Structured report-completeness card (N01)"]
    # N02: 本次运行的身份与公开配置档案。SQLite 恢复保留原 ID/配置/时间；
    # 旧断点缺失时标示未记录，不得以恢复时配置伪装原配置。
    run_metadata: Annotated[dict, "Run identity and public config profile (N02)"]
